-d C:\Users\Admin\OneDrive\Desktop\Intern_Docs\intern\TangNano-4K-example-main\key_blink\impl\gwsynthesis\key_blink.vg
-p GW1NSR-4C-QFN48P-6
-pn GW1NSR-LV4CQN48PC6/I5
-cst C:\Users\Admin\OneDrive\Desktop\Intern_Docs\intern\TangNano-4K-example-main\key_blink\src\key_blink.cst
-cfg C:\Users\Admin\OneDrive\Desktop\Intern_Docs\intern\TangNano-4K-example-main\key_blink\impl\pnr\device.cfg
-sdc C:\Users\Admin\OneDrive\Desktop\Intern_Docs\intern\TangNano-4K-example-main\key_blink\src\key_blink.sdc
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
